language: generic

sudo: required

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t prashanth1261/dockerdotnet -f dockerfile .

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-dotnet"
  env: "Dockerdotnet-envß"
  bucket_name: "elasticbeanstalk-us-west-2-848819479142"
  bucket_path: "docker-dotnet"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY