FROM mcr.microsoft.com/dotnet/sdk:3.1

WORKDIR /src/app

COPY . .

RUN dotnet restore

#RUN dotnet build

#RUN dotnet publish -c release -o /app/ReleaseArtifacts

#WORKDIR /app

#EXPOSE 5000-5001

#EXPOSE 6000

#ENV ASPNETCORE_URLS="http://*:5000"

#// "applicationUrl": "https://0.0.0.0:5000/",

CMD ["dotnet", "watch", "run"]